### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mosse**
Corrects totally erroneous lack of basic grammar.

### CODE REVIEW

**Comment by KalevRK** [comment]
I am deeply relieved that someone has caught this issue.

**Comment by nsluss** [comment]
I don't believe that piper is a proper noun here. If you can provide some research, maybe look into the history of the story and find out if piper was the individual's name, it can be merged in.

**Comment by mosse** [comment]
When most people think of fairy tales, they typically conjure up images of idealized Prince Charmings and magical hair-braiding birds. However, if you've ever indulged a passing fancy of childhood nostalgia by picking up a copy of the Grimm brothers' original tales, you might have been startled by the contents inside. These stories are far from the bright and shiny, happily-ever-after ones your parents read to you as a child or that you saw in classic Disney movies. They can be exceptionally dark -- and as grim as their namesakes.
The Grimm brothers started collecting centuries-old, German folklore in the 19th century. Their interests in philology and linguistics drew them to write down the fascinating and culturally revealing stories that, up to that time, spread chiefly through oral storytelling. In that way, you could say that the Grimm brothers didn't set these tales down to paper for the particular purpose of entertaining children. And, although the tales themselves revolve around magical events and carry morals, many weren't geared specifically toward children as much as they were for the Germanic culture as a whole. However, the stories became popular among children, so they were toned down for that audience.
But the original, unbowdlerized Grimm stories still carry relevance. Not only are they fascinating peeks into the psyche of the German people of the Middle Ages, but certain stories actually help us make sense of mysterious and bizarre historical events.
This thought might be unsettling. Indeed, the Grimm stories are so dark that the suggestion one might carry a grain of truth is horrifying. However, in the case of the "Pied Piper of Hamelin," this seems to be the case.
Before we get into the theories and historical evidence behind the story, let's go over the story in detail. And we wouldn't suggest snuggling into bed and expecting to be lulled to sleep.
For th­ose who thought the simplistic morals of Grimm tales were just for kids, "The Pied Piper of Hamelin" will probably convince you otherwise. In addition to its dark content, this is a cautionary tale about governance as well as taking responsibility for financial agreements.
The story takes place in 1284 in the Germanic town of Hamelin (now known as Hameln). At this time, the town was suffering from a severe rat infestation. The town and its mayor were at a loss when a stranger came into town. He wore slightly bizarre, pied (multicolored) clothing and carried a musical pipe. He told the people he'd heard about their rat problem and that he could rid the rats from the town -- that is, in exchange for a fee.
After agreeing to the sum, the piper took out his instrument and started playing a ditty. His song magically lured the rats to him: They came running and congregated around him. After he was convinced that he'd attracted all of the town's rats, he walked toward the nearby Weser River. There, with the rats following him all the way, he walked right into the water. The entranced rats continued blindly and dove right in, where they all drowned.
The townspeople celebrated, but they refused to pay the piper what they promised. He left, furious at the villagers and planning retribution. He got his revenge on the fateful date of June 26, which was both Saint John Day and Saint Paul Day. Dressed in hunter's attire and a red hat, the piper returned to the town, playing another song on his pipe. When the town's children heard the tune, they all flocked to him, in a similar trance as the rats. The children followed the piper out of the town and to a mountain cave, where they were never heard from again. Interestingly, the Grimm story makes a note that the mayor's grown daughter was among the group of children, which readers might infer was an act of revenge aimed directly at the mayor.
The Grimm brothers go on to say that the townspeople put an inscription on the town hall to commemorate what happened.
Evidence of the Real Pied Piper
We'd a­ll love to dismiss this story as mere fairy tale and pure fiction. However, scholars generally agree that something horrible happened in the town of Hamelin to spawn the story. Though there might not have been a piper with magical musical talents, we can safely assume that some tragedy ensued. And, as you might expect, the scholars are basing this on more evidence than just the Grimm brothers' story itself.
Supposedly, the people put up a stained glass window in their church around 1300 that depicted a group of children and a motley-clad fellow. On the glass was an inscription that read, "On the day of John and Paul 130 children in Hamelin went to Calvary and were brought through all kinds of danger to the Koppen mountain and lost" [source: Zipes]. Interestingly, this inscription didn't mention anything about a piper. Accounts of the window have been found, but the window itself seems to have been destroyed.
In what's known as the Lüneburg Manuscript, which was written more than a century after the window is thought to have been constructed, a monk by the name of Heinrich of Herferd gives an account of what happened. He wrote that a man who was about 30 years old came to the town playing a flute and led the children out [source: Zipes]. By 1603, the town erected the façade of what's known now as the Pied Piper House. On the façade, there's an inscription similar to the one that was reputedly etched on the window -- but this one explicitly mentions a pied piper.
But the suggestion of rats having anything to do with the tragedy didn't come until later. It's not too far-fetched that rats would be connected to the incident; rat infestations were certainly a problem around the 13th century and ratcatcher was a common profession.
So what do historians really think could have happened on that fateful day?
Theories About the Origin of the Pied Piper
The townspeople of Hamelin -- and particularly the children -- were probably stricken by a horrible event in the 13th century. One of the most common theories about what happened was that the town's youth suffered from some epidemic. Historians suggest that if a widespread epidemic did occur, the townspeople would have buried the children in a large common grave, which the story depicts as the site of their disappearance [source: Dirckx].
The nature of this disease is disputed. Because rats are featured in the story, scholars think it might have been a disease that spread from rodents, like the bubonic plague. Some even suggest an early version of the Black Death infected them. The piper's pied clothing might have evolved from the idea that the visitor had splotchy skin lesions brought on by the disease. Another theory states that the dancing children in the story may have been exhibiting symptoms similar to those of Huntington's disease.
But if the young people were all infected, one can reasonably question why no adults were. One theory states that the children weren't afflicted with disease but rather struck out on an ill-fated children's crusade. If this is true, it probably happened a few decades earlier when groups of young people around Europe were known to participate in the Crusades. They would leave to follow one child who claimed to have a vision from God that ordered them to march to the Holy Land and win it back for Christendom.
And some people interpret the Grimm story quite differently. They claim that the children lived and came out the other end of the cave in Transylvania. This points to the idea that the children went east to form their own colony. Fairy tale scholar Jack David Zipes substantiates this notion with documents that show evidence that someone came to Hamelin around that time looking for recruits to colonize areas of eastern Europe [source: Zipes].
Whatever happened to the children, it seems to have been traumatizing enough for the people of Hamelin to produce this tale. Even if scholars never uncover the truth, perhaps we'd do well to simply heed the lessons in this cautionary tale.

**Comment by KalevRK** [comment]
I'd like to submit a pull request to fix typos in Mark's comment.

**Comment by sdwebster** [comment]
We will concede that when speaking of the Pied Piper himself, in so many words, we must treat his full name as a proper noun, and capitalize it as Mr. Mark "mosse" Macdonald has suggested; however, given the context of the situation and the intent to refer to Fantasyland in the most oblique way possible, we feel that when not explicitly Pied, he is no Piper but rather a piper, c.f. Led Zeppelin's allusion in the lyrics to "Stairway to Heaven", as reprinted at: 

https://play.google.com/music/preview/Thhet5jtvzdxkti7vc62o2fiajq?lyrics=1&utm_source=google&utm_medium=search&utm_campaign=lyrics&pcampaignid=kp-lyrics

http://www.azlyrics.com/lyrics/ledzeppelin/stairwaytoheaven.html

http://www.songlyrics.com/led-zeppelin/stairway-to-heaven-lyrics/

**Comment by nsluss** [comment]
:+1: @sdwebster

**Comment by mosse** [comment]
Excuse me???

**Pull request closed without merging**
